import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface HomeProps {
  data: string
}

const Home: NextPage<HomeProps> = ({ data }) => {
  console.log('data', data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>

        <p>
          <img src="fidodido.gif" height={200} />
        </p>

        <p className={styles.description}>
          {data}
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/suwarnoong/cfdsa-pre-course" className={styles.card}>
            <h2>Repository &rarr;</h2>
            <p>Click here to redirect to github repository.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const texts = [
    'Logic will get you from A to B. Imagination will take you everywhere.',
    'There are 10 kinds of people. Those who know binary and those who don\'t.',
    'There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies and the other is to make it so complicated that there are no obvious deficiencies.',
    'It\'s not that I\'m so smart, it\'s just that I stay with problems longer.',
    'It is pitch dark. You are likely to be eaten by a grue.',
  ]
  const randomText = texts[Math.floor(Math.random() * texts.length)];
  return { props: { data: randomText } }
}

export default Home
